### ISSUE TITLE
NPE when detecting Quirk for H2

### ISSUE THREAD

**Issue by mbknor** [aaberg/sql2o#155]
Version: 1.5.2
When using H2-datasource like this:

      new Sql2o(datasource);

I get:

     java.lang.NullPointerException: null
        at org.sql2o.quirks.spi.QuirksProviderImpl.forObject(QuirksProviderImpl.java:22)
        at org.sql2o.quirks.QuirksDetector.forObject(QuirksDetector.java:29)
        at org.sql2o.Sql2o.<init>(Sql2o.java:78)

**Comment by javaguruen** [comment]
I get the same NPE in 
`QuirksProviderImpl:22  if (className.startsWith("oracle.jdbc.")) return oracleQuirks.q;`

I have a `H2LiquibaseDataSourceFactory `that is used. `getClass()` returns "`no.hamre.H2LiquibaseDataSourceFactory`" but `getClass().getCanonicalNamre()` returns null and causes NPW.
