### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by medcl** [aaberg/sql2o#159]
[error] application - error
play.api.Application$$anon$1: Execution exception[[NoSuchElementException: null]]
    at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10-2.2.1.jar:2.2.1]
    at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10-2.2.1.jar:2.2.1]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [play_2.10-2.2.1.jar:2.2.1]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [play_2.10-2.2.1.jar:2.2.1]
    at scala.Option.map(Option.scala:145) [scala-library.jar:na]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [play_2.10-2.2.1.jar:2.2.1]
Caused by: java.util.NoSuchElementException: null
    at sun.misc.CompoundEnumeration.nextElement(CompoundEnumeration.java:59) ~[na:1.7.0_60-ea]
    at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:349) ~[na:1.7.0_60-ea]
    at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:439) ~[na:1.7.0_60-ea]
    at org.sql2o.quirks.QuirksDetector.forURL(QuirksDetector.java:17) ~[sql2o-1.5.1.jar:na]
    at org.sql2o.Sql2o.<init>(Sql2o.java:78) ~[sql2o-1.5.1.jar:na]
    at com.xx.utils.xx.xx(xx.java:26) ~[na:na]

**Comment by ScalaWilliamTeralytics** [comment]
Getting this error here for some reason as well. Would be nice if this were merged.

**Comment by jsk** [comment]
Workaround: use 'Sql2o(ds, new NoQuirks())', i.e. force Sql2o to use empty quirks and avoid quirks detection.
