### ISSUE TITLE
java.sql.Date used as POJO at executeAndFetchFirst

### ISSUE THREAD

**Issue by foror** [aaberg/sql2o#212]
conn.createQuery("SELECT date FROM foo_table").executeAndFetchFirst(java.sql.Date.class);

java.sql.Date will be used as POJO and trying to call setDate(int) at java.util.Date (java.sql.Date extends it). But field at table is "date date NOT NULL" is not integer. As result:

```java
Exception in thread "main" java.lang.IllegalArgumentException: Cannot convert type class java.sql.Date to class java.lang.Integer
	at org.sql2o.converters.NumberConverter.convert(NumberConverter.java:38)
	at org.sql2o.converters.NumberConverter.convert(NumberConverter.java:6)
	at org.sql2o.DefaultResultSetHandlerFactory$1.setProperty(DefaultResultSetHandlerFactory.java:42)
	at org.sql2o.DefaultResultSetHandlerFactory$4.handle(DefaultResultSetHandlerFactory.java:180)
	at org.sql2o.PojoResultSetIterator.readNext(PojoResultSetIterator.java:34)
	at org.sql2o.ResultSetIteratorBase.safeReadNext(ResultSetIteratorBase.java:87)
	at org.sql2o.ResultSetIteratorBase.hasNext(ResultSetIteratorBase.java:52)
	at org.sql2o.Query.executeAndFetchFirst(Query.java:482)
	at org.sql2o.Query.executeAndFetchFirst(Query.java:469)
```

**Comment by dimzon** [comment]
https://github.com/aaberg/sql2o/blob/master/core/src/main/java/org/sql2o/DefaultResultSetHandlerFactory.java#L219

try
```
conn.createQuery("SELECT date AS my_value FROM foo_table").executeAndFetchFirst(java.sql.Date.class);
```

**Comment by dimzon** [comment]
btw. Need to avoid to search any setters/getters for well-known types like Long, Integer, Date etc....
