### ISSUE TITLE
Provider org.sql2o.quirks.H2QuirksProvider not found

### ISSUE THREAD

**Issue by miroslavivanov1988** [aaberg/sql2o#227]
When I migrated to version 1.6.0-RC1 the problem occurred:

org.sql2o.quirks.QuirksProvider: Provider org.sql2o.quirks.H2QuirksProvider not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.sql2o.quirks.QuirksDetector.forObject(QuirksDetector.java:42)
	at org.sql2o.Sql2o.<init>(Sql2o.java:67)

I am using Mysql database.

**Comment by neilgrover** [comment]
Same issue here. I'm using Postgres.

`Caused by: java.util.ServiceConfigurationError: org.sql2o.quirks.QuirksProvider: Provider org.sql2o.quirks.H2QuirksProvider not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239) ~[?:1.8.0_51]
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185) ~[?:1.8.0_51]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372) ~[?:1.8.0_51]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_51]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_51]
	at org.sql2o.quirks.QuirksDetector.forURL(QuirksDetector.java:27) ~[sql2o-1.6.0-RC1.jar:?]
	at org.sql2o.Sql2o.<init>(Sql2o.java:47) ~[sql2o-1.6.0-RC1.jar:?]
`

**Comment by neilgrover** [comment]
When I instruct Sql2o to use the NoQuirks provider, I get errors related to Postgres not supporting "RETURNING". I take it the Postgres no quirks provider has been removed correct?

**Comment by neilgrover** [comment]
Hey @miroslavivanov1988 I just figured out that Sql2o 1.6 puts the quirks classes into a separate artifact/dependency. I added it to my project and used PostgresQuirks as usual and things are now working.

See: http://mvnrepository.com/artifact/org.sql2o.extensions/sql2o-postgres/1.6.0-RC1

**Comment by aaberg** [comment]
@miroslavivanov1988 That is an unexpected error when using MySql. Could you provide the code that causes the error?

**Comment by neilgrover** [comment]
FYI I get the same error ( org.sql2o.quirks.H2QuirksProvider not found ) when using Postgres if I don't specify any Quirks implementation to the Sql2o constructor.

**Comment by aaberg** [comment]
I Have release version 1.6.0-RC2 with a fix for this issue. Could you guys try it out, and check if it fixes the problem for you?

**Comment by miroslavivanov1988** [comment]
It works, thank you!
