### ISSUE TITLE
Failure populating nested, private fields (java.lang.IllegalAccessException)

### ISSUE THREAD

**Issue by nikku** [aaberg/sql2o#233]
In my project setup Sql2o fails to set nested, private fields via [`PojoMetadata#getValueOfProperty`](https://github.com/aaberg/sql2o/blob/sql2o-1.5.4/core/src/main/java/org/sql2o/reflection/PojoMetadata.java#L156):

```
org.sql2o.Sql2oException: could not read value of field triggers on class class test.A
	at org.sql2o.reflection.PojoMetadata.getValueOfProperty(PojoMetadata.java:163)
	at org.sql2o.reflection.Pojo.setProperty(Pojo.java:43)
        ...
	Caused by: java.lang.IllegalAccessException: Class org.sql2o.reflection.PojoMetadata can not access a member of class test.A with modifiers "private"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Field.get(Field.java:390)
	at org.sql2o.reflection.PojoMetadata.getValueOfProperty(PojoMetadata.java:161)
	... 42 more
```

Do not know what is exactly going on wrong here because my setup is exactly identical to the one you have put up in [this test case](https://github.com/aaberg/sql2o/blob/sql2o-1.5.4/core/src/test/java/org/sql2o/Sql2oTest.java#L594). Maybe it is a cross-jar security policy in Java 8 or the like?

__Data Object:__

```java
public class A {
  private String name;
  
  private Nested nested = new Nested();
}
```

__Query:__

```java
c.createQuery("SELECT a.name, a.foo as \"nested.foo\" FROM a").executeAndFetch(A.class);
```

Do you have an idea what may be wrong?

While I am not sure about the actual problem, I know there is an easy fix. We could simply make the field accessible programatically before access:

```java
if (!field.isAccessible()) {
  field.setAccessible(true);
}
```

I could provide a PR for that.

**Comment by nikku** [comment]
Ahhhh, sorry for the noise. That seems to be [already fixed](https://github.com/aaberg/sql2o/blob/master/core/src/main/java/org/sql2o/reflection/FieldGetter.java#L18) with the upcoming release.
