### ISSUE TITLE
Compatibility with MySQL JDBC driver v6.0.2

### ISSUE THREAD

**Issue by fromgate** [aaberg/sql2o#243]
Hello!
I tried to create test connection to database and got an exception:

```
> org.sql2o.Sql2oException: Could not acquire a connection from DataSource - The server time zone value 'MSK' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
        at org.sql2o.Connection.createConnection(Connection.java:291)
        at org.sql2o.Connection.<init>(Connection.java:51)
        at org.sql2o.Sql2o.open(Sql2o.java:225)
        at ru.nukkit.test.Test.onCommand(Test.java:104)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:193)
        at cn.nukkit.Server.dispatchCommand(Server.java:630)
        at cn.nukkit.command.CommandReader.run(CommandReader.java:70)
Caused by: java.sql.SQLException: The server time zone value 'MSK' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:695)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:663)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:653)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:638)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:606)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:624)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:620)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:68)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1683)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:656)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:349)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:221)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at org.sql2o.GenericDatasource.getConnection(GenericDatasource.java:62)
        at org.sql2o.Connection.createConnection(Connection.java:288)
        ... 7 more
Caused by: com.mysql.cj.core.exceptions.InvalidConnectionAttributeException: The server time zone value 'MSK' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:54)
        at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
        at com.mysql.cj.jdbc.util.TimeUtil.getCanonicalTimezone(TimeUtil.java:118)
        at com.mysql.cj.mysqla.MysqlaSession.configureTimezone(MysqlaSession.java:308)
        at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:2474)
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:1817)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1673)
        ... 14 more
```

Downgrading to MySQL JDBC driver 5.1.39 solved this problem. 

Is Sql2o compatible with MySQL JDBC connector 6.0.2?

**Comment by aaberg** [comment]
This is an issue with the MySql driver, and not sql2o.
According to [this stackoverflow thrad](http://stackoverflow.com/questions/26515700/mysql-jdbc-driver-5-1-33-time-zone-issue), you might need to explicitly specify timezone in you jdbc url.

```
jdbc:mysql://localhost/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
```

Hope this helps?

**Comment by fromgate** [comment]
Thank you for answer. 
I will use 5.1.39, until they fix in newer version of JDBC Driver :)

**Comment by Sharabaddin** [comment]
Use this solve https://gist.github.com/Sharabaddin/9d3ba65785e89624068cc99877a7f2c5

**Comment by Arunkumarvarada** [comment]
Thank you , it helped.
I was using 5.1.6, recently used 6.0.6 of jdbc driver

**Comment by PaulBrains** [comment]
&serverTimezone=UTC
that's your secret.

**Comment by avijit0907** [comment]
jdbc:mysql://localhost/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC


This will work

**Comment by MounirBoulwafa** [comment]
> jdbc:mysql://localhost/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
> 
> This will work

thank you very much
