### ISSUE TITLE
I try to run my app that uses sql2o with Java 6 but I keep getting an error NoClassDefFoundError 

### ISSUE THREAD

**Issue by bonniec11** [aaberg/sql2o#269]
I know Autocloseable was introduced in Java 7, but is there a way to make sql2o compatible with java 6? Our Websphere Application Server apps run with java 6 

Exception in thread "main" java.lang.NoClassDefFoundError: java.lang.AutoCloseable
	at java.lang.ClassLoader.defineClass(ClassLoader.java:273)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:74)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:538)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$300(URLClassLoader.java:77)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1041)
	at java.security.AccessController.doPrivileged(AccessController.java:488)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:427)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:701)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:680)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:358)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:663)
	at org.sql2o.Sql2o.open(Sql2o.java:198)
	at com.ibm.procesador.service.NotificacionService.notificarUsuarios(NotificacionService.java:55)
	at com.ibm.procesador.Notificar.notificar(Notificar.java:13)
	at com.ibm.procesador.Notificar.main(Notificar.java:9)
Caused by: java.lang.ClassNotFoundException: java.lang.AutoCloseable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:432)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:701)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:680)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:358)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:663)
	at java.lang.ClassLoader.defineClassImpl(Native Method)

**Comment by mvysny** [comment]
Oracle Java 6 is dead; IBM java 6 will be dead this year. I'm not sure whether there is any merit of supporting such old platform.

**Comment by zapodot** [comment]
Sad to hear that your still stuck with Java 6... Sql2o requires Java 7 to run so I guess you are out of luck :-( 
Closing this issue
