### ISSUE TITLE
Oracle11g: executeBatch has exception

### ISSUE THREAD

**Issue by liwei6797** [aaberg/sql2o#30]
It's all right  when used mysql. But throws exceptions when uses oracle 11.2.0.1. The driver is ojdbc6.jar. It's normal when I used PreparedStatement.

Caused by: java.lang.ArrayIndexOutOfBoundsException
    at java.lang.System.arraycopy(Native Method)
    at oracle.jdbc.driver.T4CRowidAccessor.unmarshalOneRow(T4CRowidAccessor.java:205)
    at oracle.jdbc.driver.T4C8Oall.readRXD(T4C8Oall.java:648)
    at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:328)
    at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:186)
    at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:521)
    at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:205)
    at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1008)
    at oracle.jdbc.driver.OraclePreparedStatement.executeForRowsWithTimeout(OraclePreparedStatement.java:9870)
    at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:9974)
    at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:213)
    at org.sql2o.tools.NamedParameterStatement.executeBatch(NamedParameterStatement.java:340)
    at org.sql2o.Query.executeBatch(Query.java:411)
    ... 6 more

**Comment by Donaldhan** [comment]
@liwei6797 ，how to solve?
