### ISSUE TITLE
Can't add ON DELETE CASCADE to forein key when creating table, using PostgreSQL.

### ISSUE THREAD

**Issue by GlenGGG** [aaberg/sql2o#348]
I am trying to use sql2o to create a table with a foreign key and add ON DELETE CASCADE to the foreign key. Here is the code to create the parent table, posts:
```
  String sql = "CREATE TABLE IF NOT EXISTS posts("
      + "uuid CHAR(36) NOT NULL PRIMARY KEY,"
      + "user_id CHAR(36)," 
      + "title VARCHAR(50) NOT NULL,"
      + "price NUMERIC(12, 2) NOT NULL," 
      + "description VARCHAR(5000),"
      + "category Category NOT NULL,"
      + "location VARCHAR(100) NOT NULL,"
      + "create_time TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,"
      + "update_time TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP"
      + ");";
  conn.createQuery(sql).executeUpdate();
```

Here is the code to create the child table, images:

```
  String sql = "CREATE TABLE IF NOT EXISTS images("
      + "img_id CHAR(36) NOT NULL PRIMARY KEY,"
      + "post_id CHAR(36) NOT NULL,"
      + "url VARCHAR(500) NOT NULL,"
      + "FOREIGN KEY (post_id) "
      + "REFERENCES posts(uuid) "
      + "ON DELETE CASCADE" // When I remove this line, everything works fine
      + ");";
  conn.createQuery(sql).executeUpdate();
```

When I only run the code that creates the parent table, posts, it works fine. When I run the code that creates the child table, images, it shows errors:

```
[main] WARN org.sql2o.Connection - Could not roll back transaction. message: {}
org.postgresql.util.PSQLException: Cannot rollback when autoCommit is enabled.
    at org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:867)
    at org.sql2o.Connection.rollback(Connection.java:132)
    at org.sql2o.Connection.onException(Connection.java:76)
    at org.sql2o.Query.executeUpdate(Query.java:658)
    at util.Database.createImagesTable(Database.java:116)
    at util.Database.createPostsTableWithSampleData(Database.java:97)
    at util.Database.main(Database.java:37)
Exception in thread "main" org.sql2o.Sql2oException: Error in executeUpdate, ERROR: syntax error at or near "RETURNING"
    at org.sql2o.Query.executeUpdate(Query.java:659)
    at util.Database.createImagesTable(Database.java:116)
    at util.Database.createPostsTableWithSampleData(Database.java:97)
    at util.Database.main(Database.java:37)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "RETURNING"
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2510)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2245)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:311)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
    at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
    at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:125)
    at org.sql2o.Query.executeUpdate(Query.java:653)
    ... 3 more

Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "RETURNING"
```

When I remove "ON DELETE CASCADE" from the child table, it works fine. When I run these SQLs directly using a PostgreSQL client, it works fine. I have checked the sql2o's doc and issues, I found no related solutions. The version of sql2o is 1.6.0, the version of PostgreSQL is 13.2.

**Comment by GlenGGG** [comment]
Never mind, I fixed it using PostgresQuirks.
