### ISSUE TITLE
How to use Kotlin data class in v1.7.0 or later?

### ISSUE THREAD

**Issue by yusukezzz** [aaberg/sql2o#373]
My english is very poor, sorry.

Thank you for making great library!

I recently upgraded to v1.8.0 from v1.6.0 and noticed that the code that used kotlin data class as pojo stopped working.
This change seems to have occurred since v1.7.0.

[sample project](https://github.com/yusukezzz/kotlin-sql2o-data-class-test)

Data Class Definition
```
data class User(val id: Int, val name: String)
```

v1.6.0 outputs
```
[User(id=1, name=foo), User(id=2, name=bar)]
```

but in v1.7.0
```
Exception in thread "main" org.sql2o.Sql2oException: Could not find parameter-less constructor of class class org.example.User
	at org.sql2o.reflection.ReflectionObjectConstructorFactory.newConstructor(ReflectionObjectConstructorFactory.java:24)
	at org.sql2o.reflection.FactoryFacade.newConstructor(FactoryFacade.java:80)
	at org.sql2o.reflection.PojoMetadata.initializePropertyInfo(PojoMetadata.java:99)
	at org.sql2o.reflection.PojoMetadata$Cache.evaluate(PojoMetadata.java:244)
	at org.sql2o.reflection.PojoMetadata$Cache.evaluate(PojoMetadata.java:241)
	at org.sql2o.tools.AbstractCache.get(AbstractCache.java:49)
	at org.sql2o.reflection.PojoMetadata.getPropertyInfoThroughCache(PojoMetadata.java:81)
	at org.sql2o.reflection.PojoMetadata.<init>(PojoMetadata.java:68)
	at org.sql2o.DefaultResultSetHandlerFactoryBuilder.newFactory(DefaultResultSetHandlerFactoryBuilder.java:61)
	at org.sql2o.Query.newResultSetHandlerFactory(Query.java:539)
	at org.sql2o.Query.executeAndFetch(Query.java:585)
	at org.example.MainKt.main(Main.kt:32)
	at org.example.MainKt.main(Main.kt)
```

Kotlin's data class is very useful and I want to use it as a POJO as before, is it possible to fix this behavior...?

**Comment by aaberg** [comment]
Hi @yusukezzz,

Thanks for reporting this. I need to investigate the issue, and then I will get back to you.

And, by the way, I think your English is quite good🙂

**Comment by aaberg** [comment]
Hi again @yusukezzz,

I finally got around to looking into this. The issue is that Kotlin compiles a data class into the equivalent of a Java class, where all properties are set in the constructor; hence, there are no empty constructors on a data class. 

Sql2o requires an empty constructor to work because, as far as I'm aware, it is impossible to get the names of constructor parameters through reflection, making it impossible to map database columns to constructor parameters.

I'm not sure why it worked for you with Sql2o 1.6.0. Has Kotlin changed the way it compiles data classes since then?

If you have any tips or ideas that prove me wrong, I would very much like to hear them. It is a bummer that Sql2o doesn't work with data classes.

**Comment by weeklynote** [comment]
已收到，我会尽快回复你！
                     ——刘劲字

**Comment by aaberg** [comment]
No problem. It was an interesting issue to investigate. Thanks for the sample project 👍🏼
